version: "2"
services:
    web_server:
        restart: always
        container_name: web_server
        image: nginx:latest
        ports:
        - "8777:80"
        volumes:
        - "./conf/client.conf:/etc/nginx/conf.d/default.conf"
        - "./frontend:/usr/share/nginx/html"
        - "./php-client:/php-client"
        - "./downloads:/downloads"
        links:
        - "client:client"
    client:
        restart: always
        container_name: client
        image: php:7.1-fpm
        volumes:
        - "./php-client:/php-client"
        - "./downloads:/downloads"
        links:
        - "file_server:file_server"
    file_server:
        restart: always
        container_name: file_server
        image: nginx:latest
        ports:
        - "8778:80"
        volumes:
        - "./conf/server.conf:/etc/nginx/conf.d/default.conf"
        - "./blocker:/usr/share/nginx/html"
        - "./php-server:/php-server"
        - "./files:/files"
        links:
        - "server:server"
    server:
        restart: always
        container_name: server
        image: php:7.1-fpm
        volumes:
        - "./php-server:/php-server"
        - "./files:/files"
